config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :posts
    resources :users
    resources :admin_users

    root to: "posts#index"
  end

  resources :posts
  devise_for :users, skip: [:registrations]
  root 'static#homepage'
end

app/models/admin_user.rb
class AdminUser < User
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  validates_presence_of :date, :rationale
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :posts
  
  validates_presence_of :first_name, :last_name

  def full_name
    last_name.upcase + ", " + first_name.upcase
  end
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    def update
      params[:admin].delete(:password) if params[:admin][:password].blank?
      super
    end
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    def update
      params[:user].delete(:password) if params[:user][:password].blank?
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to @post, notice: 'Post Created succesfully'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post Updated succesfully'
    else
      render :edit
    end
  end

  def show; end

  def destroy
    @post.delete
    redirect_to posts_path, notice: 'Post Deleted succesfully'
  end

  private

  def post_params
    params.require(:post).permit(:date, :rationale)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(path)
    "active" if current_page?(path)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overtime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= render 'shared/nav' %>
          <%= yield %>
        </div>
      </div>
    </div>
    <%= js add_gritter(flash[:notice], title: "Overtime Notification", sticky: false) %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, class: "form-group row" do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: "Overtime Notification", sticky: false) %>
    <% end%>
  <% end %>

  <div class="form-group">
    <%= f.label :date %>
    <%= f.date_field :date, class: "form-control form-control-lg" %>
  </div>
  <div class="form-group">  
    <%= f.label :post %>
    <%= f.text_area :rationale, class: "form-control form-control-lg" %>
  </div>
  <%= f.submit 'Save', class: "btn btn-primary btn-block" %>
<% end %>

app/views/posts/_post.html.erb
<tr>
  <td>
    <%= post.id %>
  </td>
  <td>
    <%= post.date %>
  </td>
  <td>
    <%= post.user.full_name %>
  </td>
  <td>
    <%= truncate(post.rationale) %>
  </td>
  <td>
    <%= link_to 'Edit', edit_post_path(post), id: "edit_#{post.id}", class: "btn btn-sm btn-outline-secondary" %>
  </td>
  <td>
    <%= link_to 'Delete', post_path(post), method: :delete, id: "delete_post_#{post.id}_from_index", data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" %>
  </td>
</tr>

app/views/posts/edit.html.erb
<h2 class="text-primary">
  Edit
</h2>

<%= render 'form' %>

app/views/posts/index.html.erb
<h2 class="text-primary">
  Posts
</h2>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>
        #
      </th>
      <th>
        Date
      </th>
      <th>
        User
      </th>
      <th>
        Rationale
      </th>
    </tr>
  </thead>
  <tbody>
    <%= render @posts %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h2 class="text-primary">
  New
</h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= @post.inspect %>

app/views/shared/_nav.html.erb
<div class="logo">
  <h1>Time Tracker</h1>
</div>

<ul class="custom-nav nav nav-tabs">
  <li class="nav-item active">
    <a href="/" class="nav-link <%= active?(root_path) %>">Home</a>
  </li>
  <li class="nav-item">
    <a href="/posts" class="nav-link <%= active?(posts_path) %>">Time Entries</a>
  </li>
  <li class="nav-item">
    <a href="/posts/new" class="nav-link <%= active?(new_post_path) %>", id="new_post_from_nav">New Entry</a>
  </li>
  <li class="nav-item dropdown ml-md-auto">
    <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Account</a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
      <%= link_to "TODO:Admin Dashboard", root_path, class: "dropdown-item" %>
      <div class="dropdown-divider">
      </div>
      <%= link_to "Log Out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
    </div>
  </li>
</ul>